-- =============================================================================
-- 002: dim_customer — SCD TYPE 2 (the centerpiece of this sprint)
-- =============================================================================
-- THE PROBLEM THIS SOLVES:
-- A customer's segment, address, and credit band change over time. If we simply
-- overwrote the old value (that's SCD Type 1), we would destroy history and be
-- unable to answer the single most important question in bank analytics:
--
--     "What did we know about this customer AT THE TIME we made the decision?"
--
-- Fair-lending audits ask exactly that. So does any honest analysis of "did our
-- underwriting standards drift?". Overwriting makes those questions unanswerable.
--
-- HOW TYPE 2 WORKS:
-- When a tracked attribute changes, we do NOT update the row. We:
--   1. Close the existing row  (set valid_to = change date, is_current = false)
--   2. Insert a NEW row        (valid_from = change date, valid_to = 9999-12-31)
-- The customer now has multiple rows, each valid for a window of time.
--
--     customer_key | customer_id   | segment  | valid_from | valid_to   | is_current
--     1            | CUST_00000042 | mass     | 2022-01-01 | 2024-03-15 | false
--     2            | CUST_00000042 | affluent | 2024-03-15 | 9999-12-31 | true
--
-- Facts join to the version valid AT THE FACT'S DATE — that's point-in-time
-- correctness. A 2023 transaction joins to key 1 (mass); a 2025 one to key 2.
--
-- WHY 9999-12-31 INSTEAD OF NULL FOR AN OPEN ROW?
-- Because it makes range queries simple and index-friendly:
--     WHERE txn_date >= valid_from AND txn_date < valid_to
-- With NULL you would need COALESCE or OR IS NULL in every single query, which
-- is easy to get wrong and can defeat index usage.
-- =============================================================================

CREATE TABLE IF NOT EXISTS curated.dim_customer (
    -- SURROGATE KEY: meaningless integer, generated by us.
    -- Why not just use customer_id? Because with Type 2, one customer_id maps to
    -- MANY rows. The surrogate key is what uniquely identifies "this version of
    -- this customer", and it's what facts point at.
    customer_key        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- NATURAL / BUSINESS KEY: how the source system identifies this customer.
    -- Kept as an attribute, never as the primary key.
    customer_id         TEXT        NOT NULL,

    -- Descriptive attributes
    first_name          TEXT        NOT NULL,
    last_name           TEXT        NOT NULL,
    full_name           TEXT        NOT NULL,
    age                 SMALLINT,
    annual_income       NUMERIC(14,2),
    credit_score        SMALLINT,
    credit_band         TEXT,        -- derived: poor/fair/good/excellent
    dti                 NUMERIC(6,3),
    segment             TEXT,        -- mass / affluent / private
    join_date           DATE,
    home_branch_id      TEXT,

    -- ---- SCD TYPE 2 MACHINERY ----
    valid_from          DATE        NOT NULL,
    valid_to            DATE        NOT NULL DEFAULT DATE '9999-12-31',
    is_current          BOOLEAN     NOT NULL DEFAULT TRUE,
    row_hash            TEXT        NOT NULL,   -- change detection (see below)

    -- Audit columns: when did OUR pipeline create/modify this row?
    -- Distinct from valid_from/valid_to, which are about BUSINESS time.
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_dim_customer_validity CHECK (valid_to > valid_from)
);

COMMENT ON TABLE curated.dim_customer IS
    'Customer dimension, SCD Type 2. Grain: one row per customer per version '
    'of tracked attributes. Join facts on the version valid at the fact date.';

COMMENT ON COLUMN curated.dim_customer.row_hash IS
    'Hash of tracked attributes. Comparing hashes is how we detect a real change '
    'without writing a 10-column comparison in every merge.';

-- ---- INDEXES, and the reasoning behind each ----

-- The single most important constraint in a Type 2 dimension:
-- a business key may have AT MOST ONE current row. This PARTIAL UNIQUE index
-- enforces it at the database level, so a buggy pipeline cannot silently create
-- two "current" versions of the same customer.
-- (A partial index only covers rows matching the WHERE clause — smaller and
-- faster than indexing every historical row.)
CREATE UNIQUE INDEX IF NOT EXISTS uq_dim_customer_current
    ON curated.dim_customer (customer_id)
    WHERE is_current;

-- Point-in-time lookups: "the version of customer X valid on date D".
CREATE INDEX IF NOT EXISTS idx_dim_customer_pit
    ON curated.dim_customer (customer_id, valid_from, valid_to);

-- Analysts filter/group by segment constantly.
CREATE INDEX IF NOT EXISTS idx_dim_customer_segment
    ON curated.dim_customer (segment) WHERE is_current;

-- =============================================================================
-- THE UNKNOWN MEMBER
-- =============================================================================
-- Every dimension gets a row with key -1 meaning "unknown / not yet arrived".
-- WHY? Because facts sometimes reference a dimension record that hasn't loaded
-- yet (a "late-arriving dimension"). Your options are:
--   (a) reject the fact          -> you lose real money movement, unacceptable
--   (b) leave the FK null        -> INNER JOINs silently drop those rows, and
--                                   your totals are quietly wrong
--   (c) point it at the unknown member -> the fact is counted, and the problem
--                                   is VISIBLE as "Unknown" on the dashboard
-- (c) is the only honest answer. Wrong-but-visible beats missing-and-silent.
-- =============================================================================
INSERT INTO curated.dim_customer (
    customer_id, first_name, last_name, full_name,
    valid_from, valid_to, is_current, row_hash
)
SELECT '-1', 'Unknown', 'Unknown', 'Unknown Customer',
       DATE '1900-01-01', DATE '9999-12-31', TRUE, 'unknown'
WHERE NOT EXISTS (
    SELECT 1 FROM curated.dim_customer WHERE customer_id = '-1'
);
